### ISSUE TITLE
parse / validate option

### ISSUE THREAD

**Issue by arechnitzer** [PreTeXtBook/pretext-cli#199] opened 2022-03-03 22:37 UTC
Is it possible to add a "validate source" option without doing a full build?  `pretext parse` or `pretext validate`

(btw - the cli is really useful)

**Comment by StevenClontz** [comment] 2022-03-03 22:46
Closing as a duplicate of https://github.com/PreTeXtBook/pretext-cli/issues/29 

@oscarlevin can probably remind us of why this is non-trivial (I think it's an issue with LXML?)

**Closed by StevenClontz** 2022-03-03 22:46 UTC

**Comment by arechnitzer** [comment] 2022-03-03 23:03
oops. sorry. should have searched harder.
