### ISSUE TITLE
Codechat is broken when path includes spaces?

### ISSUE THREAD

**Issue by StevenClontz** [PreTeXtBook/pretext-cli#471] opened 2023-06-29 15:04 UTC
https://github.com/PreTeXtBook/pretext-cli/blob/970e22961edab501e4213216c4dbfb72b3f74661/tests/test_project.py#L215

Modifying that line to use spaces seems to break Codechat (I think somewhere in the pipeline it's using a URI-escaped version of the path where it needs literal spaces rather than `%20`s).

**Comment by bjones1** [comment] 2023-07-03 17:40
I'd be happy to track this down and fix it, but I'm getting test failures from the current code for this test (`test_demo_html_build`). before I introduces spaces to reproduce the CodeChat failure. Any help would be appreciated!

**Comment by bjones1** [comment] 2023-07-18 17:17
This is still on my to-do list, but blocked by issues in #458 (that test fails because the publication file doesn't exist, but we assume a publication file name by default).

**Comment by bjones1** [comment] 2023-07-20 14:45
This is fixed by 373595171203ec325842cce162a26dc8aae9d5ab.

**Closed by bjones1** 2023-07-20 14:45 UTC
