### ISSUE TITLE
Document `pretext publish`

### ISSUE THREAD

**Issue by oscarlevin** [PreTeXtBook/pretext-cli#220] opened 2022-04-01 20:34 UTC
Sean points out [here](https://groups.google.com/g/pretext-dev/c/-25dLmASEKw) that we don't document the `pretext publish` feature.

**Comment by StevenClontz** [comment] 2022-04-07 02:51
closing this as an almost-duplicate of #172

**Closed by StevenClontz** 2022-04-07 02:51 UTC
Labels: pretext deploy
